_ELEMENT_GROUPS = {
    "ROBO": ["ROBO", "ROBO_FLYING"],
    "ROBO_DEAD": ["ROBO_FALLING", "ROBO_LASER"],
    "ROBO_OTHER": ["ROBO_OTHER", "ROBO_OTHER_FLYING"],
    "ROBO_OTHER_DEAD": ["ROBO_OTHER_FALLING", "ROBO_OTHER_LASER"],
    "ZOMBIE": ["FEMALE_ZOMBIE", "MALE_ZOMBIE"],
    "LASER_MACHINES": [
            "LASER_MACHINE_CHARGING_LEFT",
            "LASER_MACHINE_CHARGING_RIGHT",
            "LASER_MACHINE_CHARGING_UP",
            "LASER_MACHINE_CHARGING_DOWN",
            "LASER_MACHINE_READY_LEFT",
            "LASER_MACHINE_READY_RIGHT",
            "LASER_MACHINE_READY_UP",
            "LASER_MACHINE_READY_DOWN",
        ],
    "LASERS": [
            "LASER_LEFT",
            "LASER_RIGHT",
            "LASER_UP",
            "LASER_DOWN",
        ],
    "WALLS": [
            "ANGLE_IN_LEFT",
            "WALL_FRONT",
            "ANGLE_IN_RIGHT",
            "WALL_RIGHT",
            "ANGLE_BACK_RIGHT",
            "WALL_BACK",
            "ANGLE_BACK_LEFT",
            "WALL_LEFT",
            "WALL_BACK_ANGLE_LEFT",
            "WALL_BACK_ANGLE_RIGHT",
            "ANGLE_OUT_RIGHT",
            "ANGLE_OUT_LEFT",
            "SPACE"
        ],
    "PERKS": [
            "UNSTOPPABLE_LASER_PERK",
            "DEATH_RAY_PERK",
            "UNLIMITED_FIRE_PERK",
        ],
    "WALKABLE": [
            "FLOOR",
            "START",
            "ZOMBIE_START",
            "EXIT",
            "GOLD"
        ],
}
